config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#index'

  resources :products do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Home < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_name)
  before_save(:titleize_country_of_origin)

  private
    def titleize_name
      self.name = self.name.titleize
    end

    def titleize_country_of_origin
      self.country_of_origin = self.country_of_origin.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true, length: {in: 50...250}
  validates :rating, presence: true, numericality: {  only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :email, presence: true
  before_save(:titleize_author)
  private
    def titleize_author
      self.author = self.author.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @products = Product.all
    @reviews = Review.all
    render :index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :except => [:index, :show] do
    unless current_user && current_user.admin
      flash[:notice] = "You are not authorized to visit that page"
      redirect_to products_path
    end
  end

  def index
    @products = Product.all.sort_by { |hash| hash[:name] }
    render :index
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully created"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated"
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted"
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :only => [:destroy] do
    unless current_user && current_user.email == Review.find(params[:id]).email || current_user.admin
      flash[:notice] = "You are not authorized to visit that page"
      redirect_to products_path
    end
  end

  before_action :only => [:new, :create] do
    unless current_user && current_user.admin == false
      flash[:notice] = "Only users can create and update reviews"
      redirect_to products_path
    end
  end

  before_action :only => [:edit, :update] do
    unless current_user && current_user.admin == false && current_user.email == Review.find(params[:id]).email
      flash[:notice] = "You cannot edit other reviews"
      redirect_to products_path
    end
  end


  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully created"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated"
      redirect_to product_review_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully deleted"
    redirect_to product_path(@product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
<div class="box">
  <div class="center-text">
    <img src="\assets\hitomi.png" height="200" alt="Hitomi's Sushi">
    <p>Select any option in the nav bar to get started.</p>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <% object.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/layouts/_products_form.html.erb
  <%= render "layouts/errors", :object => @product %>

  <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :cost %>
    <%= f.number_field :cost, step: 0.01 %>
    <%= f.label :country_of_origin %>
    <%= f.text_field :country_of_origin %>
    <%= f.submit :Submit %>
  <% end %>

app/views/layouts/_reviews_form.html.erb
  <%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %><br>
  <%= f.text_field :author%><br>
  <%= f.label :rating %><br>
  <%= f.select :rating, [1,2,3,4,5] %><br>
  <%= f.label :content_body %><br>
  <%= f.text_area :content_body, size: "40x10" %><br>
  <%= f.hidden_field :email, :value => current_user.email %>
  <%= f.submit :Submit %>
<% end %>

<%= link_to "Back", product_path(@product) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hitomi's Sushi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="nav">
    <div id="nav-text">
      <% if current_user && current_user.admin %>
        <%= link_to "Home", root_path %> | <%= link_to "Products", products_path %> | <%= link_to "Settings", '/users/edit' %> | <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> | Role: Admin | <%= current_user.email %>
      <% elsif current_user %>
        <%= link_to "Home", root_path %> | <%= link_to "Products", products_path %> | <%= link_to "Settings", '/users/edit' %> | <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> | <%= current_user.email %>
      <% else %>
          <%= link_to "Home", '/' %> | <%= link_to "Products", products_path %> | <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
  </div>

  <body>
  <div class="container">
    <div id="flash">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/reviews_form.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <% object.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1>Edit Product</h1>
  <%= render "layouts/products_form"%>
</div>

<%= link_to "Back", product_path %>

app/views/products/index.html.erb
<div class="container">
  <div class="center-text">
    <h1>Products</h1>
    <div class="red-link">
      <% if current_user && current_user.admin %>
        <%= link_to "Create new product", new_product_path %><br>
      <% end %>
    </div>
    <% if @products.any? %>
      <% @products.sort %>
      <% @products.each do |product| %>
        <%= link_to product.name, product_path(product) %><br>
      <% end %>
    <% else %>
      <p>There are no products yet. </p>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>
  <%= render "layouts/products_form"%>
</div>

<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<div class="container">
  <div class="center-text">
    <div id="product-name">
      <h1><strong><%= @product.name %></strong></h1>
    </div>
    <h3>Price: $<%= @product.cost %></h3>
    <h3>Country of origin: <%= @product.country_of_origin %></h3>
    <div class="red-link">
      <% if current_user && current_user.admin %>
        <%= link_to "Edit Product", edit_product_path(@product) %>
        |
        <%= link_to "Delete Product", product_path(@product),
        :data => {:confirm => "Are you sure?", :method => "delete"} %>
      <% elsif current_user %>
        <%= link_to "Add a review", new_product_review_path(@product) %>
      <% else %>
        <p>Sign in to add a review for this product.</p>
      <% end %>
    </div>
  </div>
  <div id="reviews">
    <% if @product.reviews.any? %>
      <h3><strong>Product reviews:</strong></h3>
        <% @product.reviews.each do |review| %>
          <p><strong>Rating: <%= review.rating %></strong></p>
          <p>Author: <%= review.author %></p>
          <p><%= review.content_body %></p>
          <div class="red-link">
            <%= link_to "See details", product_review_path(@product, review) %><br><br>
          </div>
        <% end %>
    <% else %>
      <p>There are no reviews for this product yet.</p>
    <% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<div class="container">
  <h1>Edit Review</h1>
  <%= render "layouts/reviews_form"%>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New Review</h1>
  <%= render "layouts/reviews_form"%>
</div>

app/views/reviews/show.html.erb
<div class="container">
  <p>Rating: <%= @review.rating %></p>
  <p>Author: <%= @review.author %></p>
  <p><%= @review.content_body %></p>


  <% if current_user && current_user.admin %>
    <%= link_to "Delete Review", product_review_path(@product, @review),
    :data => {:confirm => "Are you sure?", :method => "delete"} %>
  <% elsif current_user &&  @review.email == current_user.email %>
    <%= link_to "Edit Review", edit_product_review_path(@product, @review) %><br>
    <%= link_to "Delete Review", product_review_path(@product, @review),
    :data => {:confirm => "Are you sure?", :method => "delete"} %>
  <% end %>

  <div class="back">
    <%= link_to "Back", product_path(@product) %>
  </div>
</div>